### PR TITLE
PR for the branch (use-redux-in-components)

### PR DESCRIPTION
**Pull request by HamzaAnwar1998**
In this milestone, I have created an initial state with some books in the redux store then I used the state to display them in components.

**NOTE: Without knowingly, I have done most of the work in the previous exercise**

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @HamzaAnwar1998,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- PR is good ✅.
- Linters are passing ✅.
- Good readme file✅.


## Required Changes ♻️
_Check the comments under the review._
- Hello @HamzaAnwar1998 Nice job on Redux however you have missed some parts in the  redux:
1. Import Redux Provider and your store in the main component of your React app.
2. the button in the `categories` check button should dispatch a message `under construction`.

Capture web_17-5-2022_133048_github com (1)
Capture web_17-5-2022_133128_github com


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HamzaAnwar1998** [comment]
Hi @dasileker 

I have imported Provider in the index.js, isn't index.js the main component?

**Comment by dasileker** [comment]
> Hi @dasileker 
> 
> I have imported Provider in the index.js, isn't index.js the main component?

It's the app.js

**Review by dasileker — APPROVED** [review]
### **Hi @HamzaAnwar1998,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
